spring.application.name=SS13-B5
server.port=8081
server.servlet.context-path=/pharmacy

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/pharmacy_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=LLL2006

# Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update